### ISSUE TITLE
React app "Module parse failed: Identifier directly after number"

### ISSUE THREAD

**Issue by Naapperas** [syntax-tree/hast-util-to-text#4]
### Initial checklist

- [x] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-highlight: 5.0.0, hast-util-to-text: 3.0.0

### Steps to reproduce

> npx create-react-app test-app
*copy "react-markdown": "^7.0.1" and "rehype-highlight": "^5.0.0" to package.json (from another project that used 'npm install')*
npm install
edit App.js:
```js
import logo from './logo.svg';
import './App.css';

import rehypeHighlight from 'rehype-highlight'
import ReactMarkdown from 'react-markdown'

const markdown = "```js\
import React from 'react'\
import ReactDOM from 'react-dom'\
import ReactMarkdown from 'react-markdown'\
import rehypeHighlight from 'rehype-highlight'\
\
ReactDOM.render(\
  <ReactMarkdown rehypePlugins={[rehypeHighlight]}>{'# Your markdown here'}</ReactMarkdown>,\
  document.querySelector('#content')\
)\
```";

// taken from https://remarkjs.github.io/react-markdown/

function App() {
  return <ReactMarkdown rehypePlugins={[rehypeHighlight]}>{markdown}</ReactMarkdown>
}

export default App;
```
>npm start

### Expected behavior

React launching and a page appearing with syntax highlighting.

### Actual behavior

Crash.
![image](https://user-images.githubusercontent.com/23704084/131229772-7abf43f4-066a-4260-a42b-694ca2cfe3f1.png)
I went through the node_modules folder to look at the source code of the module and tracked the issue to line 399, not the one specified in the image (difference probably due to removing comments when serving the app, I'm not really sure).

I found a [react-markdown-loader](https://github.com/hugmanrique/react-markdown-loader) that could possibly fix the "additional loader" problem but that package in itself brings more trouble so I'm excluding it from my project.

In addition, I found an [SO thread](https://stackoverflow.com/questions/68904475/why-i-can-build-my-react-app-but-cannot-start-it) talking about a different `rehype` module that uses `hast-util-to-text` experiencing the same error as I am.

### Runtime

Node v16

### Package manager

npm v7

### OS

Linux

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
This is probably due to the numeric separators added here: https://github.com/syntax-tree/hast-util-to-text/commit/c6f5df6f4e6c21fa4ab00ab273692bec56c77693#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346.
As I understand it, that language feature has been [shipping for a while](https://github.com/tc39/proposal-numeric-separator#implementations) and there’s a babel plugin for [4 years already too](https://babeljs.io/docs/en/babel-plugin-proposal-numeric-separator).
Are you using old versions of CRA/webpack/Babel?

**Comment by LOVEwitch** [comment]
I have the same problem with ‘Identifier directly after number’ use umi

**Comment by wooorm** [comment]
What is an "umi"?

**Comment by ChristianMurphy** [comment]
Umi.js is a next.js like framework https://umijs.org

**Comment by gcalabria** [comment]
Any news on this issue?

**Comment by wooorm** [comment]
I’ve published a fix but I would recommend everyone to not use ancient babel versions. Babel has supported this for more than 4 years already.
